### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by MrAwesome2127** [MrAwesome2127/prework-study-guide#1]
# HTML

## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide website
When I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed

**Comment by Nishant9771** [comment]
There are some Listed Websites where you can check once :

freecodecamp
MDN WEB
codecademy
coursera
w3school
or last you can explore any repositories regading that on github.

**Comment by MrAwesome2127** [comment]
Thanks @Nishant9771. This is a prework for KU Boot Camp to prepare for class this September. I appreciate you taking the time to add your comments. I will check this out.

**Comment by MrAwesome2127** [comment]
Completed Module #3.1, closing issue card.
